import type { CaseStructure } from '../types.ts'

// Case three: Naboth's vineyard (1 Kings 21) — three moments the player puts in order, four papers,
// and a second block, the prophet's words. One spot carries no cite: the Law scroll, whose sources
// are Deuteronomy and Leviticus. The empty chairs at the gate are set dressing, not a spot, since
// no verse names them (#26).
export const vineyard = {
  id: 'vineyard',
  thumb: 'vineyard',
  passages: [{ book: '1KI', chapter: 21 }],
  moments: [
    {
      id: 'vineyard',
      picture: 'vineyard.jpg',
      size: [900, 1125],
      spots: [
        {
          id: 'man-rows',
          box: [8, 30.8, 31.5, 64],
          words: ['taken-possession'],
          person: 'p1',
          cites: '21:16',
        },
        { id: 'cord', box: [34.5, 41, 33.6, 25], words: ['garden'], cites: '21:2' },
        {
          id: 'prophet',
          box: [71, 34.2, 21, 45.3],
          words: ['elijah', 'killed'],
          cites: '21:17-19',
        },
        { id: 'stain', box: [8, 17.1, 22.6, 11.6], words: ['blood', 'dogs'], cites: '21:19' },
        {
          id: 'balcony',
          box: [76, 3.2, 16, 18.5],
          words: ['jezebel'],
          person: 'p2',
          paper: 'note',
          cites: '21:14',
        },
      ],
    },
    {
      id: 'bedchamber',
      picture: 'bedchamber.jpg',
      size: [900, 1125],
      spots: [
        { id: 'window', box: [0, 0, 28, 25], words: ['vineyard'], cites: '21:1' },
        {
          id: 'man-bed',
          box: [1, 25, 37, 19],
          words: ['turned-away'],
          person: 'p1',
          cites: '21:4',
        },
        { id: 'tray', box: [0, 50, 23, 11], words: ['would-not-eat'], cites: '21:4' },
        { id: 'woman', box: [51, 4, 37, 47], words: [], person: 'p2', cites: '21:5-7' },
        {
          id: 'seal',
          box: [61.5, 49.5, 15, 11],
          words: ['ahab', 'seal'],
          paper: 'seal',
          cites: '21:8',
        },
        { id: 'sheets', box: [46, 57, 36, 11], words: ['letters'], cites: '21:8' },
        { id: 'purse', box: [78, 59, 14, 12], words: ['silver'], cites: '21:2' },
      ],
    },
    {
      id: 'gate',
      picture: 'gate.jpg',
      size: [900, 1125],
      spots: [
        { id: 'crowd', box: [0, 58, 100, 42], words: ['the-people', 'fast'], cites: '21:12' },
        { id: 'stones', box: [38, 12, 24, 18], words: ['stoned'], cites: '21:13' },
        { id: 'seated', box: [36, 30, 26, 28], words: [], person: 'p3', cites: '21:12' },
        { id: 'accusers', box: [3, 18, 33, 44], words: ['cursed'], cites: '21:13' },
        {
          id: 'letter',
          box: [64, 27, 18, 26],
          words: ['naboth', 'the-elders', 'the-king'],
          paper: 'letter',
          cites: '21:8-10',
        },
        { id: 'law', box: [80, 36, 20, 12], words: ['inheritance'], paper: 'law' },
      ],
    },
  ],
  words: {
    ahab: 'name',
    jezebel: 'name',
    naboth: 'name',
    elijah: 'name',
    'turned-away': 'action',
    'would-not-eat': 'action',
    'taken-possession': 'action',
    killed: 'action',
    stoned: 'action',
    cursed: 'action',
    vineyard: 'noun',
    garden: 'noun',
    silver: 'noun',
    inheritance: 'noun',
    seal: 'noun',
    letters: 'noun',
    fast: 'noun',
    'the-people': 'noun',
    'the-elders': 'noun',
    'the-king': 'noun',
    blood: 'noun',
    dogs: 'noun',
  },
  faces: [
    { id: 'p1', picture: 'p1.jpg', answer: 'ahab' },
    { id: 'p2', picture: 'p2.jpg', answer: 'jezebel' },
    { id: 'p3', picture: 'p3.jpg', answer: 'naboth' },
  ],
  order: ['bedchamber', 'gate', 'vineyard'],
  blocks: [
    {
      id: 'account',
      blanks: {
        s1: 'garden',
        s2: 'vineyard',
        s3: 'inheritance',
        s4: 'jezebel',
        s5: 'the-king',
      },
    },
    { id: 'verdict', blanks: { v1: 'killed', v2: 'taken-possession' } },
  ],
} as const satisfies CaseStructure
