import type { CaseStructure } from '../types.ts'

// Case two: Naboth's vineyard (1 Kings 21) — three moments the player puts in order, four papers,
// and a second block, the prophet's words. Two spots carry no cite: the chairs, which no verse
// names, and the Law scroll, whose sources are Deuteronomy and Leviticus.
export const vineyard = {
  id: 'vineyard',
  thumb: 'vineyard',
  passages: [{ book: '1KI', chapter: 21 }],
  moments: [
    {
      id: 'vineyard',
      picture: 'vineyard.jpg',
      size: [900, 1125],
      spots: [
        {
          id: 'man-rows',
          box: [8, 12, 30, 70],
          words: ['taken-possession'],
          person: 'p1',
          cites: '21:16',
        },
        { id: 'cord', box: [34, 28, 36, 44], words: ['garden'], cites: '21:2' },
        { id: 'prophet', box: [72, 20, 26, 36], words: ['prophet'], cites: '21:17-19' },
        { id: 'stain', box: [66, 52, 34, 34], words: ['blood', 'killed', 'dogs'], cites: '21:19' },
        {
          id: 'balcony',
          box: [66, 1, 24, 15],
          words: ['jezebel', 'dead'],
          person: 'p2',
          paper: 'note',
          cites: '21:14',
        },
      ],
    },
    {
      id: 'bedchamber',
      picture: 'bedchamber.jpg',
      size: [900, 1125],
      spots: [
        { id: 'window', box: [0, 0, 33, 26], words: ['vineyard'], cites: '21:1' },
        {
          id: 'man-bed',
          box: [2, 24, 38, 22],
          words: ['face-to-the-wall'],
          person: 'p1',
          cites: '21:4',
        },
        { id: 'tray', box: [0, 50, 28, 18], words: ['would-not-eat'], cites: '21:4' },
        { id: 'woman', box: [52, 4, 40, 46], words: [], person: 'p2', cites: '21:5-7' },
        { id: 'seal', box: [66, 50, 16, 9], words: ['ahab', 'seal'], paper: 'seal', cites: '21:8' },
        { id: 'sheets', box: [44, 57, 36, 12], words: ['letters'], cites: '21:8' },
        { id: 'purse', box: [74, 58, 26, 16], words: ['silver'], cites: '21:2' },
        { id: 'lamp', box: [88, 46, 12, 12], words: ['lamp'], cites: '21:4' },
      ],
    },
    {
      id: 'gate',
      picture: 'gate.jpg',
      size: [900, 1125],
      spots: [
        { id: 'crowd', box: [0, 58, 100, 42], words: ['the-people'], cites: '21:12' },
        { id: 'stones', box: [38, 12, 24, 22], words: ['stoned'], cites: '21:13' },
        { id: 'seated', box: [36, 30, 26, 28], words: [], person: 'p3', cites: '21:12' },
        { id: 'accusers', box: [3, 18, 33, 44], words: ['two'], cites: '21:13' },
        {
          id: 'letter',
          box: [64, 27, 18, 26],
          words: ['naboth', 'fast', 'elders', 'three'],
          paper: 'letter',
          cites: '21:8-10',
        },
        { id: 'law', box: [80, 36, 20, 12], words: ['inheritance'], paper: 'law' },
        { id: 'chairs', box: [76, 44, 24, 18], words: [] },
      ],
    },
  ],
  words: {
    ahab: 'name',
    jezebel: 'name',
    naboth: 'name',
    two: 'number',
    three: 'number',
    'face-to-the-wall': 'action',
    'would-not-eat': 'action',
    'taken-possession': 'action',
    killed: 'action',
    stoned: 'action',
    dead: 'action',
    vineyard: 'noun',
    seal: 'noun',
    letters: 'noun',
    silver: 'noun',
    lamp: 'noun',
    fast: 'noun',
    elders: 'noun',
    inheritance: 'noun',
    'the-people': 'noun',
    garden: 'noun',
    prophet: 'noun',
    blood: 'noun',
    dogs: 'noun',
  },
  faces: [
    { id: 'p1', picture: 'p1.jpg', answer: 'ahab' },
    { id: 'p2', picture: 'p2.jpg', answer: 'jezebel' },
    { id: 'p3', picture: 'p3.jpg', answer: 'naboth' },
  ],
  order: ['bedchamber', 'gate', 'vineyard'],
  blocks: [
    {
      id: 'account',
      blanks: {
        s1: 'garden',
        s2: 'silver',
        s3: 'inheritance',
        s4: 'would-not-eat',
        s5: 'jezebel',
        s6: 'two',
        s7: 'stoned',
      },
    },
    { id: 'verdict', blanks: { v1: 'killed', v2: 'taken-possession' } },
  ],
} as const satisfies CaseStructure
